const Data=[

    {
        id:1,
        market:"BTC/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },
    {
        id:2,
        market:"BTC/INR",
        minimumordersize:"0.00002",
        makerfee:"0.120%",
        takerfee:"0.128%",
        status:"Enabled"
    },

    {
        id:3,
        market:"ETH/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },
    {
        id:4,
        market:"ETC/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:5,
        market:"LTC/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },
    {
        id:6,
        market:"LIC/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:7,
        market:"SHIB/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },
    {
        id:8,
        market:"SHIB/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },
    { 
        id:9,
        market:"DOGE/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },
    {
        id:10,
        market:"DOGE/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:11,
        market:"SOL/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:12,
        market:"SOL/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:13,
        market:"ADA/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:14,
        market:"ADA/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:15,
        market:"SHIB/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },
    { 
        id:16,
        market:"DOGE/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },
    {
        id:17,
        market:"DOGE/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:18,
        market:"SOL/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:19,
        market:"SOL/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:20,
        market:"ADA/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:21,
        market:"ADA/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:22,
        market:"XLM/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:23,
        market:"XLM/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },
    {
        id:24,
        market:"BNB/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:25,
        market:"BNB/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },
    {
        id:26,
        market:"NER/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:27,
        market:"NEAR/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },
    {
        id:28,
        market:"LINK/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:29,
        market:"LINK/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },
    {
        id:30,
        market:"SAND/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:31,
        market:"SAND/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },
    {
        id:32,
        market:"MANA/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:33,
        market:"MANA/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:34,
        market:"GALA/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:35,
        market:"GALA/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:36,
        market:"SUSHI/USDT",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },

    {
        id:37,
        market:"SUSHI/INR",
        minimumordersize:"0.00005",
        makerfee:"0.125%",
        takerfee:"0.125%",
        status:"Enabled"
    },
    

]

export default Data;